services:
  chat-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: chat/client
    command: node server.js
    ports:
      - "8081:8080"
  chat-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: chat/api
    command: bash -c "forever --watch src/index.js"
    ports:
      - "8082:3000"
