apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-websockets
resources:
  - manifests/namespace.yaml
  - manifests/deployment-api.yaml
  - manifests/deployment-client.yaml
  - manifests/ingress.yaml
